# Site settings
title: ErikEJ's blog
author: Erik Ejlskov Jensen
#email: your-email@example.com
description: .NET Data Access and more
baseurl: "" # the subpath of your site, e.g. /blog
url: https://erikej.github.io
twitter_username: erikej
github_username:  erikej
stackoverflow_username: "183934"
twitter:
  username: erikej
  card: summary

# Build settings
markdown: GFM
theme: minima
show_excerpts: true
google_analytics: UA-7366519-3
plugins:
  - jekyll-feed
  - jekyll-seo-tag
gist:
  noscript: false
future: true 
jailed: false
